name: Leviathianic
title: Leviathianic
url: http://leviathianic.com
author: Fernando

# Minimal Mistakes overrides
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
_engine: jekyll/minimal-mistakes-jekyll
minimal_mistakes_skin: "air"

# Build Settings
markdown: kramdown
paginate: 5

plugins:
  - jekyll-include-cache

