name: Leviathianic
title: Leviathianic
url: http://leviathianic.com
author: Fernando

# Minimal Mistakes overrides
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
_engine: jekyll/minimal-mistakes-jekyll
minimal_mistakes_skin: "neon"

# Build Settings
markdown: kramdown
paginate: 7

plugins:
  - jekyll-include-cache
 

